const PHONE='573229432085';
const plans=[
{id:'internet-65900',cat:'internet',title:'Internet hogar',speed:'300 Mb HFC / 350 Mb Fibra*',price:'$65.900',desc:'Plan de entrada para navegación, estudio y trabajo.',benefits:['Internet hogar','Velocidad según tecnología y cobertura','Instalación indicada en oferta: $52.000'],img:'plan-3.webp',tag:'PLAN DE ENTRADA',featured:false},
{id:'fibra-89900',cat:'internet',title:'Internet Fibra',speed:'900 Megas*',price:'$89.900',desc:'Fibra óptica simétrica según cobertura.',benefits:['50% en la primera factura','Elige 1 app según oferta','Instalación sin costo indicada en oferta'],img:'plan-4.webp',tag:'FIBRA',featured:false},
{id:'fibra-79900',cat:'internet',title:'Internet Fibra',speed:'900 Megas*',price:'$79.900',desc:'Alta velocidad para hogares con varios dispositivos.',benefits:['Prime Video indicado en la oferta','Claro video con contenidos indicados','Ideal para streaming, estudio y trabajo'],img:'plan-5.webp',tag:'DESTACADO',featured:true},
{id:'tv-104900',cat:'tv',title:'Internet + TV',speed:'900 Megas* + 89 canales',price:'$104.900',promo:'$52.450 por 2 meses',desc:'Internet y televisión con entretenimiento para el hogar.',benefits:['1 decodificador','50% de descuento primeros 2 meses','Elige 1 plataforma según oferta'],img:'plan-6.webp',tag:'INTERNET + TV',featured:false},
{id:'tv-119900',cat:'tv',title:'Internet + TV',speed:'900 Megas* + 89 canales',price:'$119.900',promo:'$59.950 por 2 meses',desc:'Más entretenimiento y beneficios adicionales.',benefits:['1 dongle + 1 decodificador','Elige 2 apps según oferta','McAfee + Multiasistencia'],img:'plan-7.webp',tag:'MÁS ENTRETENIMIENTO',featured:true},
{id:'tv-121900',cat:'tv',title:'Internet + TV',speed:'900 Megas* + 89 canales',price:'$121.900',promo:'$60.950 por 2 meses',desc:'Conectividad y televisión para toda la familia.',benefits:['1 dongle + 1 decodificador','Elige 2 apps según oferta','McAfee + Multiasistencia'],img:'plan-8.webp',tag:'INTERNET + TV',featured:false},
{id:'tv-99900',cat:'tv',title:'Internet + TV',speed:'900 Megas* + TV',price:'$99.900',desc:'Una opción equilibrada de Internet y entretenimiento.',benefits:['TV 89 canales en oferta','Elige 2 apps según oferta','Instalación sin costo indicada en oferta'],img:'plan-9.webp',tag:'DESTACADO',featured:true},
{id:'tv-109900',cat:'triple',title:'Internet + TV + Voz',speed:'500 a 900 Megas*',price:'$109.900',desc:'Conectividad, televisión y telefonía para el hogar.',benefits:['1 deco HD + 1 digital/dongle','Netflix, Prime Video o Disney+ según oferta','Telefonía fija nacional ilimitada + beneficios'],img:'plan-10.webp',tag:'COMPLETO',featured:true},
{id:'tvav-129900',cat:'tv',title:'Internet + TV Avanzada',speed:'900 Megas*',price:'$129.900',desc:'Televisión avanzada, streaming y seguridad digital.',benefits:['Netflix o Amazon Prime + Win+ según oferta','McAfee Premium para 3 equipos','Elige una asistencia según oferta'],img:'plan-11.webp',tag:'TV AVANZADA',featured:false},
{id:'triple-111900',cat:'triple',title:'Internet + TV + Voz',speed:'900 Megas*',price:'$111.900',desc:'Internet, televisión nacional y telefonía ilimitada.',benefits:['Elige 1 app según oferta','TV nacional + 1 deco HD','Telefonía fija ilimitada + McAfee'],img:'plan-12.webp',tag:'TRIPLE PLAY',featured:true},
{id:'promo-106900',cat:'triple',title:'Internet + TV + Voz',speed:'900 Megas* + 89 canales',price:'$106.900',desc:'Promoción con entretenimiento y telefonía para el hogar.',benefits:['50% de descuento primeros 2 meses','Elige 1 plataforma según oferta','Incluye Win+ fútbol según pieza comercial'],img:'plan-13.webp',tag:'PROMOCIÓN',featured:true},
{id:'premium-131900',cat:'triple',title:'Internet + TV Avanzada + Voz',speed:'900 Megas*',price:'$131.900',desc:'La alternativa más completa del catálogo.',benefits:['TV avanzada + telefonía ilimitada','Netflix o Prime + Win+ según oferta','McAfee Premium + asistencia a elección'],img:'plan-14.webp',tag:'MÁS COMPLETO',featured:false}
];
function messageFor(p){return `Hola MIRED360. Vengo de la app y me interesa este plan:\n\n📶 ${p.title} — ${p.speed}\n💰 ${p.price}${p.promo?` (${p.promo})`:''}\n\nQuiero validar cobertura en mi dirección.\n📍 Ciudad: \n🏘️ Barrio: \n🏠 Dirección: `}
function wa(text){return `https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`}
function render(filter='all'){
 const box=document.getElementById('cards');box.innerHTML='';
 plans.filter(p=>filter==='all'||p.cat===filter).forEach(p=>{
  const el=document.createElement('article');el.className='plan-card'+(p.featured?' featured':'');
  el.innerHTML=`<div class="plan-thumb"><img loading="lazy" src="assets/plans/${p.img}" alt="${p.title} ${p.price}"><span class="plan-badge">${p.tag}</span></div><div class="plan-info"><h3>${p.title}</h3><div class="plan-speed">${p.speed}</div><div class="plan-price">${p.price} <small>/mes</small></div>${p.promo?`<div class="plan-promo">${p.promo}</div>`:''}<ul class="plan-benefits">${p.benefits.map(b=>`<li>${b}</li>`).join('')}</ul><div class="plan-actions"><a target="_blank" href="${wa(messageFor(p))}">Validar cobertura</a><button data-detail="${p.id}">Ver detalle</button></div></div>`;
  box.appendChild(el);
 });
 document.querySelectorAll('[data-detail]').forEach(btn=>btn.onclick=()=>openDetail(btn.dataset.detail));
}
function openDetail(id){const p=plans.find(x=>x.id===id);if(!p)return;document.getElementById('modalContent').innerHTML=`<div class="detail-image"><img src="assets/plans/${p.img}" alt="${p.title}"></div><div class="detail-body"><span class="detail-kicker">${p.tag}</span><h2>${p.title}</h2><div class="plan-speed">${p.speed}</div><div class="detail-price">${p.price} <small>/mes</small></div>${p.promo?`<div class="plan-promo">${p.promo}</div>`:''}<p>${p.desc}</p><ul>${p.benefits.map(b=>`<li>${b}</li>`).join('')}</ul><div class="detail-note"><b>Importante:</b> la tecnología (HFC o Fibra), velocidad y disponibilidad se confirman al validar la dirección.</div><a class="detail-wa" target="_blank" href="${wa(messageFor(p))}">Validar cobertura por WhatsApp</a></div>`;const m=document.getElementById('planModal');m.classList.add('open');m.setAttribute('aria-hidden','false')}
document.querySelectorAll('.filters button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render(btn.dataset.filter)});
document.querySelectorAll('[data-jump]').forEach(btn=>btn.onclick=()=>{const f=btn.dataset.jump;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x.dataset.filter===f));render(f);document.getElementById('planes').scrollIntoView({behavior:'smooth'})});
const generic=`Hola MIRED360. Quiero validar cobertura de Internet Claro.\n📍 Ciudad: \n🏘️ Barrio: \n🏠 Dirección: `;document.getElementById('genericWa').href=wa(generic);document.getElementById('footerWa').href=wa(generic);
document.querySelector('.modal-close').onclick=()=>document.getElementById('planModal').classList.remove('open');document.getElementById('planModal').onclick=e=>{if(e.target.id==='planModal')e.currentTarget.classList.remove('open')};
render();
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).finally(()=>window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js?v=10').catch(()=>{})))}
